### ISSUE TITLE
Broken pipe in import_from_iterable 

### ISSUE THREAD

**Issue by nautilus28** [badoo/pyexasol#40]
Hi Vitaly,

I have run into this error several times when importing a large dataset using `import_from_iterable`.

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pyexasol/connection.py", line 247, in import_from_iterable
    return self.import_from_callback(cb.import_from_iterable, src, table, None, import_params)
  File "/usr/local/lib/python3.7/site-packages/pyexasol/connection.py", line 339, in import_from_callback
    raise e
  File "/usr/local/lib/python3.7/site-packages/pyexasol/connection.py", line 323, in import_from_callback
    result = callback(http_proc.write_pipe, src, **callback_params)
  File "/usr/local/lib/python3.7/site-packages/pyexasol/callback.py", line 66, in import_from_iterable
    writer.writerow(row)
BrokenPipeError: [Errno 32] Broken pipe
```

I am using pyexasol 0.6.4.

Should this be caught by the library?

Thanks.

**Comment by wildraid** [comment]
Any more exceptions from SQL thread? It normally happens if Exasol received malformed data and aborted query. But you should see the error message in separate exception.

Alternatively, error message should be available in `EXA_DBA_AUDIT_SQL`. Let's check this system table.

**Comment by nautilus28** [comment]
@wildraid your right. The actual problem was just data truncation. 

Thank you for your quick response.
