### ISSUE TITLE
Import from iterable swallows ETL exception

### ISSUE THREAD

**Issue by LennartAtExasol** [badoo/pyexasol#45]
I can not exactly pinpoint where the exception is happening.
When importing form an iterable and a string truncation occurs (ETL-3003) or an integer is out of range (ETL-3050) pyexasol is not throwing the corresponding exception. 

Instead the user is notified that the server closed the connection (Broken Pipe Error) and the program terminates. I suspect an unhandled exception somewhere in the connection.py module?

**Comment by wildraid** [comment]
@LennartAtExasol , could you attach the whole output when exception happens? You may need to scroll up a bit.

HTTP transport runs one extra thread and one extra process internally. When something goes wrong, different exceptions are happening in each component independently. However, you should be able to see all exceptions, and SQL exception should have a priority.

**Comment by LennartAtExasol** [comment]
`----------------------------------------
Exception happened during processing of request from ('213.95.157.85', 8563)
Traceback (most recent call last):
  File "C:\Users\ln\AppData\Local\Programs\Python\Python38\lib\socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "C:\Users\ln\AppData\Local\Programs\Python\Python38\lib\socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "C:\Users\ln\AppData\Local\Programs\Python\Python38\lib\socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "C:\Users\ln\AppData\Local\Programs\Python\Python38\lib\socketserver.py", line 720, in __init__
    self.handle()
  File "C:\Users\ln\AppData\Local\Programs\Python\Python38\lib\site-packages\pyexasol_utils\http_transport.py", line 128, in handle
    self.method_get()
  File "C:\Users\ln\AppData\Local\Programs\Python\Python38\lib\site-packages\pyexasol_utils\http_transport.py", line 190, in method_get
    self.wfile.write(c.compress(data))
  File "C:\Users\ln\AppData\Local\Programs\Python\Python38\lib\socketserver.py", line 799, in write
    self._sock.sendall(b)
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
----------------------------------------
Exception in thread DB Thread:
Traceback (most recent call last):
  File "C:\Users\ln\AppData\Local\Programs\Python\Python38\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Users\ln\Documents\Demo\Blockchain\Code\blocks_to_exasol.py", line 111, in run
    self.exa_connection.import_from_iterable(self.tx_input_sql_generator(), self.targets["inputs"])
  File "C:\Users\ln\AppData\Local\Programs\Python\Python38\lib\site-packages\pyexasol\connection.py", line 254, in import_from_iterable
    return self.import_from_callback(cb.import_from_iterable, src, table, None, import_params)
  File "C:\Users\ln\AppData\Local\Programs\Python\Python38\lib\site-packages\pyexasol\connection.py", line 346, in import_from_callback
    raise e
  File "C:\Users\ln\AppData\Local\Programs\Python\Python38\lib\site-packages\pyexasol\connection.py", line 330, in import_from_callback
    result = callback(http_proc.write_pipe, src, **callback_params)
  File "C:\Users\ln\AppData\Local\Programs\Python\Python38\lib\site-packages\pyexasol\callback.py", line 66, in import_from_iterable
    writer.writerow(row)
BrokenPipeError: [Errno 32] Broken pipe

Process finished with exit code 0`

This happened when the following ETL Error occured (from DB logs)
ETL-3003: [Column=5 Row=52200] [String data right truncation. String length exceeds limit of 2000 characters]

This behaviour does not seem to be deterministic.

**Comment by wildraid** [comment]
Aha, it's Windows.

Could try to run the same code on Linux / MacOS to see if it's a Windows-specific problem related to threading?

Do you have other threads running in parallel with PyEXASOL request?

**Comment by wildraid** [comment]
@LennartAtExasol , as one more quick solution, could try to find those lines in connection.pt:
https://github.com/badoo/pyexasol/blob/master/pyexasol/connection.py#L348-L349

```
            if 'sql_thread' in locals() and sql_thread.exc:
                raise sql_thread.exc
```

and replace it with:

```
            if 'sql_thread' in locals()
                sql_thread.join(1)

                if sql_thread.exc:
                    raise sql_thread.exc
```

**Comment by LennartAtExasol** [comment]
Hi, i was able to test on linux, the issue is the same.
sql_thread.join does not seem to know the timeout parameter. This exception happend on a ETL-3050 error.

```
----------------------------------------                                                                                                                                                                                                     Exception happened during processing of request from ('213.95.157.84', 8563)                                                                                                                                                                 Traceback (most recent call last):                                                                                                                                                                                                             File "/usr/lib/python3.6/socketserver.py", line 320, in _handle_request_noblock                                                                                                                                                                self.process_request(request, client_address)                                                                                                                                                                                              File "/usr/lib/python3.6/socketserver.py", line 351, in process_request                                                                                                                                                                        self.finish_request(request, client_address)                                                                                                                                                                                               File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request                                                                                                                                                                         self.RequestHandlerClass(request, client_address, self)                                                                                                                                                                                    File "/usr/lib/python3.6/socketserver.py", line 724, in __init__                                                                                                                                                                               self.handle()                                                                                                                                                                                                                              File "/usr/local/lib/python3.6/dist-packages/pyexasol_utils/http_transport.py", line 128, in handle                                                                                                                                            self.method_get()                                                                                                                                                                                                                          File "/usr/local/lib/python3.6/dist-packages/pyexasol_utils/http_transport.py", line 190, in method_get                                                                                                                                        self.wfile.write(c.compress(data))                                                                                                                                                                                                         File "/usr/lib/python3.6/socketserver.py", line 803, in write                                                                                                                                                                                  self._sock.sendall(b)                                                                                                                                                                                                                    BrokenPipeError: [Errno 32] Broken pipe                                                                                                                                                                                                      ----------------------------------------                                                                                                                                                                                                     Exception in thread DB Thread:                                                                                                                                                                                                               Traceback (most recent call last):                                                                                                                                                                                                             File "/usr/local/lib/python3.6/dist-packages/pyexasol/connection.py", line 328, in import_from_callback                                                                                                                                        result = callback(http_proc.write_pipe, src, **callback_params)                                                                                                                                                                            File "/usr/local/lib/python3.6/dist-packages/pyexasol/callback.py", line 66, in import_from_iterable                                                                                                                                           writer.writerow(row)                                                                                                                                                                                                                     BrokenPipeError: [Errno 32] Broken pipe                                                                                                                                                                                                                                                                                                                                                                                                                                                   During handling of the above exception, another exception occurred:              
Traceback (most recent call last):                                                                                                                                                                                                             File "blocks_to_exasol.py", line 116, in run                                                                                                                                                                                                   self.exa_connection.import_from_iterable(self.tx_out_sql_generator(), self.targets["outputs"])                                                                                                                                             File "/usr/local/lib/python3.6/dist-packages/pyexasol/connection.py", line 254, in import_from_iterable                                                                                                                                        return self.import_from_callback(cb.import_from_iterable, src, table, None, import_params)                                                                                                                                                 File "/usr/local/lib/python3.6/dist-packages/pyexasol/connection.py", line 342, in import_from_callback                                                                                                                                        sql_thread.join(timeout=1)                                                                                                                                                                                                               TypeError: join() got an unexpected keyword argument 'timeout'                                                                                                                                                                                                                                                                                                                                                                                                                            During handling of the above exception, another exception occurred:                                                                                                                                                                                                                                                                                                                                                                                                                       Traceback (most recent call last):                                                                                                                                                                                                             File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner                                                                                                                                                                          self.run()                                                                                                                                                                                                                                 File "blocks_to_exasol.py", line 119, in run                                                                                                                                                                                                   except ExaError:                                                                                                                                                                                                                         NameError: name 'ExaError' is not defined                                                                                                                                                                                                                                                                                                                                                                                                                                                 ^CException ignored in: <module 'threading' from '/usr/lib/python3.6/threading.py'>                                                                                                                                                          Traceback (most recent call last):                                                                                                                                                                                                             File "/usr/lib/python3.6/threading.py", line 1294, in _shutdown                                                                                                                                                                                t.join()                                                                                                                                                                                                                                   File "/usr/lib/python3.6/threading.py", line 1056, in join                                                                                                                                                                                     self._wait_for_tstate_lock()                                                                                                                                                                                                               File "/usr/lib/python3.6/threading.py", line 1072, in _wait_for_tstate_lock                                                                                                                                                                    elif lock.acquire(block, timeout):                                                                                                                                                                                                       KeyboardInterrupt               
```

the last fey lines were propably me killing the script

**Comment by wildraid** [comment]
@LennartAtExasol , ok, let's try `sql_thread.join(1)`, without word `timeout`.

This argument exists for sure: https://docs.python.org/3/library/threading.html#threading.Thread.join

**Comment by wildraid** [comment]
I have one more idea. Currently I did not "join()" the SQL thread during exception in the main thread because SQL might be potentially stuck in infinite loop.

However, we now have an `.abort()` function which might be called from the main thread if necessary. The only problem is abort() might fail too if WebSocket connection was closed or crippled in some other way. User might end up having error message with 4-5 exceptions. :)

I'll think about it a little.

**Comment by wildraid** [comment]
@LennartAtExasol , I've pushed a test branch with slightly modified exception handling (`http_transport_exc_test`): https://github.com/badoo/pyexasol/tree/http_transport_exc_test

Please give it a try. You may setup local version of pyexasol with `pip install -e .` executed from downloaded pyexasol directory.

**Comment by wildraid** [comment]
@LennartAtExasol , please try again with new version deployed today (`0.12.0+`). I've reworked exception handling for HTTP transport. Now it should always wait for SQL thread and give higher priority to SQL exceptions from it.

I still don't have "clean" Windows machine for tests.

Let's see how it goes now.
