### ISSUE TITLE
get_disk_space_usage() is failing if Exasol has just started

### ISSUE THREAD

**Issue by expobrain** [badoo/pyexasol#5]
The function `get_disk_space_usage()` in `ext.py` fails with:

```
Traceback (most recent call last):
  File "examples/13_ext.py", line 36, in <module>
    occupied_space = C.ext.get_disk_space_usage()
  File "/home/travis/build/expobrain/pyexasol/pyexasol/ext.py", line 200, in get_disk_space_usage
    row['occupied_size'] = int(row['occupied_size'])
TypeError: 'NoneType' object is not subscriptable
```

if Exasol has just started and the `$EXA_STATS_DB_SIZE` table is stil empty.

**Comment by wildraid** [comment]
Yeah, it affects automated tests. New rows appear in "$EXA_STATS_DB_SIZE" every ~30 minutes.

Fixed. Thank you!
