### ISSUE TITLE
Pandas import/export throws cannot serialize error

### ISSUE THREAD

**Issue by BeatTheBookie** [badoo/pyexasol#7]
Following script:

import pyexasol
import json
import pandas

Con = pyexasol.connect(dsn='*********:8563', user='***', password = '***')

##serialize error
data_frame = Con.export_to_pandas("SELECT * FROM STAGE.SQUAWKA_CUR_FIXTURES")

##works
#st = Con.execute("SELECT * FROM STAGE.SQUAWKA_CUR_FIXTURES")
#data_frame = pandas.DataFrame(data=st.fetchall())

print(data_frame.head())

##serialize error
#Con.import_from_pandas(data_frame,'sandbox.cur_fixtures')

##serialize error
#Con.import_from_iterable(data_frame.iterrows(),'sandbox.cur_fixtures')

throws error, when trying to export or import data into a pandas data frame.
Using the fetchall() method works and data can be loaded into a data frame.

Following trace is shown:

C:\Programmel\Continuum\Anaconda3\envs\tensorflow\python.exe "C:/Users/ado/Documents/betting db/099_dokumentation/Python/test.py"
Traceback (most recent call last):
  File "C:/Users/ado/Documents/betting db/099_dokumentation/Python/test.py", line 8, in <module>
    data_frame = Con.export_to_pandas("SELECT * FROM STAGE.SQUAWKA_CUR_FIXTURES")
  File "C:\Programmel\Continuum\Anaconda3\envs\tensorflow\lib\site-packages\pyexasol\connection.py", line 205, in export_to_pandas
    return self.export_to_callback(cb.export_to_pandas, None, query_or_table, query_params, callback_params, {'with_column_names': True})
  File "C:\Programmel\Continuum\Anaconda3\envs\tensorflow\lib\site-packages\pyexasol\connection.py", line 260, in export_to_callback
    raise e
  File "C:\Programmel\Continuum\Anaconda3\envs\tensorflow\lib\site-packages\pyexasol\connection.py", line 238, in export_to_callback
    http_proc.start()
  File "C:\Programmel\Continuum\Anaconda3\envs\tensorflow\lib\site-packages\pyexasol\http_transport.py", line 213, in start
    super().start()
  File "C:\Programmel\Continuum\Anaconda3\envs\tensorflow\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "C:\Programmel\Continuum\Anaconda3\envs\tensorflow\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Programmel\Continuum\Anaconda3\envs\tensorflow\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Programmel\Continuum\Anaconda3\envs\tensorflow\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Programmel\Continuum\Anaconda3\envs\tensorflow\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: cannot serialize '_io.FileIO' object

Process finished with exit code 1

Following versions are used:
Exasol = 6.0.0
Python = 3.6.5
rsa = 3.4.2
pandas = 0.23.0
websocket-client = 0.48.0

**Comment by wildraid** [comment]
Thank you for report.

It's definitely related to Windows "multiprocessing" module implementation lacking `fork()` and trying to serialize pipe handles created [here](https://github.com/badoo/pyexasol/blob/master/pyexasol/http_transport.py#L183).

I won't have access to Windows machines until the end of next week. I'll try a few workarounds when I can.

However, I am not really sure about the idea of "big data processing" on Windows. You're likely to hit limitations elsewhere.

**Comment by wildraid** [comment]
By the way, if you have relatively small dataset (less than 1M), standard fetching with `json_lib='rapidjson'` and `compression=True` should be okay and still better than turbodbc on weak network connection.

**Comment by BeatTheBookie** [comment]
Thanks for the fast reply!

The size of the dataset, the network connection and the transfering time from Exasol to Python does not really matter. I just searched for the easiest way to get the data from Exasol into a pandas data frame and a colleague at Exasol recommended your package.

**Comment by wildraid** [comment]
Ok, I think I know how this can be fixed. 

I can use ‘multiprocessing.Pipe’ wrapped in file-like object calling ‘send_bytes()’ and ‘recv_bytes()’. And I can test it in Linux by switching to “spawn” method.

I’ll push a small update soon.

**Comment by wildraid** [comment]
@BeatTheBookie , I've uploaded the new version.

Multiprocessing was completely replaced with basic subprocess and standard pipes. In theory, it's the most compatible way of doing inter-process communication. 

POSIX OS users should not see any difference. I've checked source code of subprocess, and it appears to use the same `os.pipe()` + binary mode approach.

Please update from pip and let me know if it works.
```
pip install --upgrade pyexasol
```

Thank you.

**Comment by BeatTheBookie** [comment]
The serialize error is now gone.
But now following error occurs:

Traceback (most recent call last):
  File "C:\Programmel\Continuum\Anaconda3\envs\tensorflow\lib\site-packages\pyexasol\connection.py", line 251, in export_to_callback
    result = callback(http_proc.read_pipe, dst, **callback_params)
  File "C:\Programmel\Continuum\Anaconda3\envs\tensorflow\lib\site-packages\pyexasol\callback.py", line 42, in export_to_pandas
    return pandas.read_csv(pipe, skip_blank_lines=False, **kwargs)
  File "C:\Programmel\Continuum\Anaconda3\envs\tensorflow\lib\site-packages\pandas\io\parsers.py", line 709, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "C:\Programmel\Continuum\Anaconda3\envs\tensorflow\lib\site-packages\pandas\io\parsers.py", line 449, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "C:\Programmel\Continuum\Anaconda3\envs\tensorflow\lib\site-packages\pandas\io\parsers.py", line 818, in __init__
    self._make_engine(self.engine)
  File "C:\Programmel\Continuum\Anaconda3\envs\tensorflow\lib\site-packages\pandas\io\parsers.py", line 1049, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "C:\Programmel\Continuum\Anaconda3\envs\tensorflow\lib\site-packages\pandas\io\parsers.py", line 1695, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas\_libs\parsers.pyx", line 565, in pandas._libs.parsers.TextReader.__cinit__
pandas.errors.EmptyDataError: No columns to parse from file

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/ado/Documents/betting db/099_dokumentation/Python/test.py", line 10, in <module>
    data_frame = Con.export_to_pandas('SELECT * FROM STAGE.SQUAWKA_CUR_FIXTURES')
  File "C:\Programmel\Continuum\Anaconda3\envs\tensorflow\lib\site-packages\pyexasol\connection.py", line 212, in export_to_pandas
    return self.export_to_callback(cb.export_to_pandas, None, query_or_table, query_params, callback_params, {'with_column_names': True})
  File "C:\Programmel\Continuum\Anaconda3\envs\tensorflow\lib\site-packages\pyexasol\connection.py", line 265, in export_to_callback
    raise sql_thread.exc
  File "C:\Programmel\Continuum\Anaconda3\envs\tensorflow\lib\site-packages\pyexasol\http_transport.py", line 37, in run
    self.run_sql()
  File "C:\Programmel\Continuum\Anaconda3\envs\tensorflow\lib\site-packages\pyexasol\http_transport.py", line 122, in run_sql
    self.connection.execute(query)
  File "C:\Programmel\Continuum\Anaconda3\envs\tensorflow\lib\site-packages\pyexasol\connection.py", line 150, in execute
    stmt._execute()
  File "C:\Programmel\Continuum\Anaconda3\envs\tensorflow\lib\site-packages\pyexasol\statement.py", line 122, in _execute
    'sqlText': self.query,
  File "C:\Programmel\Continuum\Anaconda3\envs\tensorflow\lib\site-packages\pyexasol\connection.py", line 498, in _req
    raise cls_err(self, req['sqlText'], ret['exception']['sqlCode'], ret['exception']['text'])
pyexasol.exceptions.ExaQueryError: 
(
/000.gz failed after 0 bytes. [Illegal characters found in URL],[3],[URL using bad/illegal format or missing URL]] (Session: 1603579492586972943)
    dsn         =>  192.168.164.130:8563
    user        =>  sys
    schema      =>  STAGE
    code        =>  42636
    session_id  =>  1603579492586972943
    query       =>  EXPORT (
SELECT * FROM STAGE.SQUAWKA_CUR_FIXTURES
) INTO CSV
' FILE '000.gz'
WITH COLUMN NAMES
)

**Comment by wildraid** [comment]
@BeatTheBookie , awesome, subprocess works on Windows. Now the problem is related to Windows line-endings.

I've pushed an update with direct writing to `sys.stdout.buffer` with `\n` at the end. According to manual `readline()` for binary streams is always looking for `\n`.

Please give it a try (0.3.23). It should be okay this time!
```
pip install --upgrade pyexasol
```

If you'll have any error again, please wrap it with "code" tags during reporting. It may help to preserve all the details. In order to do so, use three backticks wrapper:

```
>```
> my_code
> my_error
>```
```

Thanks!

**Comment by wildraid** [comment]
Enjoy!

I'll run all tests on Windows machine when I get back home. I am not sure about automated testing for Windows, but one-off check should be fine at this stage.

**Comment by Salehflaconi** [comment]
Hi 

i have the same error 

  raise cls_err(self, req['sqlText'], ret['exception']['sqlCode'], ret['exception']['text'])
pyexasol.exceptions.ExaQueryError: 
(
'] (Session: xxxxx)
    dsn         =>  xxxxx
    user        =>  xxxx
    schema      =>  xxxx
    code        =>  xxxx
    session_id  =>  xxxx
    query       =>  xxxx
AT 'IP' FILE '000.csv'

But with out mentioning the error code 
i don't know what is the problem 
Did you face something like that ?

**Comment by wildraid** [comment]
Hello,

@Salehflaconi , could you please open a separate issue with full error text? What are your OS and pyexasol versions? Do you run it in some special environment which overloads system STDOUT and STDERR streams?
